{% set name = "cdlib" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdlib-{{ version }}.tar.gz
  sha256: 52433dd4f7b980f78498f48dc16029801007c5e1cd0c8ac08e3a40e92c517ab0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - scikit-learn
    - tqdm
    - networkx >=3.0
    - demon
    - python-louvain >=0.16
    - nf1
    - scipy
    - pulp
    - seaborn
    - pandas
    - eva-lcd
    - bimlpa
    - markov-clustering
    - python-igraph >=0.10
    - angelcommunity
    - pooch
    - dynetx
    - thresholdclustering
    - python-levenshtein

test:
  imports:
    - cdlib
  requires:
    - pip

about:
  home: https://github.com/GiulioRossetti/cdlib
  summary: Community Discovery Library
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
